export const nft_scheme = [
  {
    id: 1,
    tag: "DT1-1",
    category: "Development Team",
    name: "Disclosure",
    question:
      "Are you Affiliated with the project or own any of the collection?",
    worksteps: [
      "A. Quesion is asking if you are affiliated with the project (part of the dev team, on payroll, partnered) or own any of it.",
      "B. If yes, explain in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "This tool is designed so that anyone can create a report for any project they are interested in. This means that a wide range of people can make them, from a newcomer learning about NFTs for the first time to experienced collectors to members of the dev team that want to produce a report and share with their community. If someone owns the NFTs they create the report for or are part of the team producing them, they have a direct financial interest in the projects success and therefore, they may be more inclined to give a higher score or make things look better than they truly are. Because of this, we are starting the NFT Tool with a disclosure where the report creator can explain any relationship they may have with the team or financial interest in the project so that they are completely transparent with the readers. Now, can we guarantee that people will be honest and disclose everything? Of course not. Someone could write whatever they want and it would be very difficult to verify. But there are also a lot of honest people out there who value their credibility and would happily share their interest in the project. This disclosure is for those people.  Lastly, just because someone owns the project doesn't mean they would necessarily make an inaccurate or misleading report.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 2,
    tag: "DT2-2",
    category: "Development Team",
    name: "Whitepaper",
    question: "Does the project have a whitepaper?",
    worksteps: [
      "A. Check the website to see if the project has a whitepaper.",
      "B. Read the whitepaper.",
      "C. Consider including some highlights from the paper in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 0.5 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "We created a poll for this point and the majority of respondents felt that a whitepaper is a must have for an NFT project with the second highest response being that it is not a deal breaker but it is nice to have. There are some who buy NFTs purely for the art, and there is nothing wrong with that. If it is purely art then a whitepaper is probably not too relevant or important. But there are others who buy NFTs because of utility, use case, roadmap, or other factors. In these instances, having a whitepaper that breaks everything down is important. It should provide all the information that their investor needs to know to make an informed decision. So in these instances, having a solid whitepaper is a good sign for the project.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 3,
    tag: "DT3-3",
    category: "Development Team",
    name: "Website",
    question:
      "Is the website updated and reflects the current state of the project?",
    worksteps: [
      "A. Confirm that the website is legitimate by confirming it matches the project's official social media.",
      "B. Check if there are broken links or outdated information.",
      "C. Use Whois Lookup domain tracker (https://whois.domaintools.com/) to verify the domain authenticity.",
      "D. Check if the website has up to date links to their various social media channels.",
      "E. Summarize your findings in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 1.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Although it is important to have social media profiles, a website helps the project look more credible and professional. It allows the team to showcase their product, the team, partnerships, and their commitments, generally through a roadmap. It is also a place where you can promote your social media presence and encourage people to join your network and spread the word, which is extremely important for the success of the project. Things such as poor grammar and spelling, lack of a privacy policy, no reference to social media presence or general errors can greatly affect the credibility of the project, and steer people away from it.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 4,
    tag: "DT4-4",
    category: "Development Team",
    name: "Utility",
    question:
      "Can you identify the utility of the project after reading the whitepaper/litepaper and reviewing website info?.",
    worksteps: [
      "A. Read the whitepaper and review website info. There is usually a section in both that discusses utility.",
      "B. Check the roadmap of the project for commitments and goals regarding the utility of the project.",
      "C. Summarize the utility in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "There are some who buy NFTs purely for the art, and there is nothing wrong with that. But there are others who buy NFTs because of utility. For those who are buying for utility, it can come in many ways. Be it a token distributed to holders of the NFT, tiered airdrops if one holds a minimum amount of NFT of the project, raffles or even whitelist spots on future mints. Utility can even give access to real world events, as it was the case of Bored Apes where all the holder were invited to a yacht party. Utility is something you should consider, so that the long term investors have incentives to hold the NFT, avoiding becoming a buy and dump project. In the end, the projects that will truly last and thrive are the ones with real utility (usefulness). Something that fills a real-world need, solves a problem, does something better than anyone else, etc. Projects that do not can definitely go up a lot in value as we have seen time and time again, but most of the time their shot-term success is driven by hype which can be fleeting and can go as quickly as it comes. So for many, identifying a project with solid utility is a good step in the research process in determining if it is something you should risk your hard-earned money on. So if you read the whitepaper or website and you still have no idea what the use case of the NFT is, chances are it doesn't really have one. ",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 5,
    tag: "DT5-5",
    category: "Development Team",
    name: "Originality",
    question:
      "Is the project an original or is it derivative of another project?",
    worksteps: [
      "A. Read the website & whitepaper (if available).",
      "B. Assess if it is materially similar to other NFT projects you are aware of.",
      "C. If you are unsure, consider reviewing the projects discord to see if this has been discussed by the community.",
      "D. Write your explanation in the box below.",
    ],

    options: [
      { id: 1, name: "Derivative", value: 0.0 },
      { id: 2, name: "Original", value: 1.25 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Many people value originality vs blatant copying of something someone else has already done. This can be a tricky topic, since many things build on top of each other and the lines between copying something and building upon it can become blurred. So this will require you to use a little personal judgment. Does the project look like a copy of something done on another chain like Ethereum? Does the artwork look extremely similar to something else you have already seen? Is the utility it claims the exact same thing that many others have done before? These are all things to be considered when determining if it is derivative or not and can impact others' opinions of the project and therefore, their willingness to invest in it. ",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 6,
    tag: "DT6-6",
    category: "Development Team",
    name: "Roadmap",
    question:
      "Is there an updated roadmap defined for the project with medium to long term planning?",
    worksteps: [
      "A. Review project website to check if there is a roadmap section.",
      "B. If there is a roadmap, confirm that it is updated.",
      "C. Make sure the goals set on the roadmap seem plausible.",
      "D. Summarize your findings in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 1.5 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Having a well-defined roadmap with the team's commitments is important to ensure that the project has a future beyond the minting event. However, the NFT scene is changing rapidly, and having enough medium to long-term goals set on the roadmap is also important. A roadmap without appealing goals can lead to quick money grabs where people will buy and dump, not only making the floor price go down but also increasing the secondary market availability.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 7,
    tag: "DT7-7",
    category: "Development Team",
    name: "Anonymous Team",
    question:
      "Is the Team known or has been doxxed by a trusted doxxing platform?",
    worksteps: [
      "A. Review project website to check if team is listed. ",
      "B. Review project discord to check for information regarding the team.",
      "C. List each member listed in box below or the platform responsible for the doxxing.",
      "D. Summarize your findings in the box below.",
    ],

    options: [
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Practically all exit scams and rug pulls are performed by anonymous teams. Why do you suppose that is? I think that the simplest answer is that if you are going to commit a crime, it is infinitely easier to get away with it if nobody knows who you are. The exact same reason that bank robbers choose to wear a mask. If you commit fraud and steal millions from investors, the police will hunt you down and you will face consequences for your actions. At the very least, you will be labeled a charlatan and will not be able to easily do the same thing in the future. If you commit fraud and steal millions of investors while remaining completely anonymous, you will never really face any consequences for your actions and will be able to continue doing it again and again. Now, does this mean that any dev team that chooses to remain anonymous is 100% going to commit fraud and steal? Of course not. There are lots of brilliant, hard-working, and trustworthy developers out there that might prefer to be anonymous, and that is their right. But the good teams who choose to remain anonymous are normalizing the practice which leaves the door wide open for the bad teams to steal over and over again. We as a community should not be willing to invest in or use any dApp where the dev team has chosen to be anonymous, as this potential for fraud will always be present. We have no way to sort the trustworthy teams from the untrustworthy and are left in a situation where we are essentially just hoping that people do the right thing.  If a dev team wants us to trust them enough to use and invest in their products, they must give us a reason to trust them. Revealing themselves is a loud and clear message to the investing community that they will do right by us and if they do not, they will suffer the consequences. The good teams who choose to remain anonymous are normalizing the practice which leaves the door wide open for the bad teams to steal over and over again.  Many teams prefer to keep themself anonymous but resort to trusted doxxing platforms in order to assure the community that there is a real team behind the project. These doxxing processes generally consist of complex KYC mechanisms that include features such as video calls, ID confirmation, and other checks, in order to assure the authenticity of the team.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 8,
    tag: "DT8-8",
    category: "Development Team",
    name: "Identity Verification",
    question: "Can you verify that the Development Team are real people?",
    worksteps: [
      "A. List each person obtained in project website in box below",
      "B. If links to LinkedIn Github, or other websites are provided, click through each link and review the information to determine if it looks genuine. Genuine profiles would likely have a long history, several contacts, current information, recommended skills,  etc.",
      "C. If no links are provided, you will need to manually search. Begin with Google for general information. Check LinkedIn, Facebook, Instagram, Github, and twitter to see if you can locate a profile that matches each person.",
      "D. If you have reason to doubt the profiles you have found were authentic, use google image search for each profile picture that was provided. Instructions for using Google search can be found here (https://support.google.com/web search/answer/1325808?hl=en&co=GENIE.Platform%3DDesktop). Ensure image is not a stock photo and can be traced to a matching social media platform. ",
      "E. For any profiles found using workstep C, perform the review from Workstep B.",
      "F. If you discover the team info is fake, go back to TD1 and change the answer to Yes",
      "G. If you are able to find information for core members or a large number of them, it is OK if some others cannot be verified. ",
      "H. Copy links to supporting information in the box below to support your review.",
    ],

    options: [
      { id: 1, name: "Yes", value: 0.5 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Simply verifying that there are people listed on the project website is insufficient. It is not unheard of for a team to list fake people on the website to give the appearance they have all revealed their identities when they have not. Because of this, you must do a little work verifying that each person listed is real. Ideally there will be links included with each name and photo in the teams section that direct you to each person's LinkedIn account, Github, Medium, or any other socials that are used to corroborate identity and professional credentials. Many teams will provide these freely because they want to make it easy for you to verify them. If links are not provided, that is frustrating but not necessarily a red flag. Go through the worksteps that are listed here to try to find various social media accounts to confirm their identity and credentials. Even if you do find a LinkedIn account or social media account, that doesn't guarantee that the information is legitimate. Any good scammer would have gone through the trouble of creating a fake identity for each person they listed in the website. You will need to use some of your past experience and common sense to review what is available and determine if it is legitimate. You have likely seems hundreds of LinkedIn profiles or Twitter/IG accounts and can spot things that look funny. Hardly any contacts. A ton of contacts but barely and activity. There are all kinds of things that can appear unusual and are too many to list here, but you will need to review the information and determine if you think it appears legitimate. And typically finding several sources online that can be compared and cross referenced to each other provides additional assurance that the person is real (e.g. has LinkedIn profile with several connections and people who have attested to a certain skill the person has, has a Facebook or IG account with similar pictures that appears legitimate, has a few articles written about them from various third party publications that you are familiar with).  If you do determine that there are people listed in the website but they appear to be fake people, that is going to be a huge red flag. Honesty and reputation are extremely important and a team that is willing to mislead on this would likely be willing to mislead in other areas as well. It is possible that there are reasonable explanations or it is a rare instance where a person has no online presence, but anyone should proceed extremely cautiously if they are having trouble verifying the teams identities. ",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 9,
    tag: "DT9-9",
    category: "Development Team",
    name: "Plagiarism",
    question: "Was there any plagiarism in the whitepaper? ",
    worksteps: [
      "A. Copy the information in the whitepaper and paste it into the following website (https://www.check-plagiarism.com/).",
      "B. Note that this site is not perfect. Many of the citations for plagiarism may come from the project itself and should be ignored.",
      "C. Include a summary of the results into the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 0.75 },
      { id: 3, name: "N/A", value: 0.75 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Honesty and reputation are extremely important and a team that is willing to mislead or cheat in one area would likely be willing to mislead and cheat in other areas as well. Stealing someone's ideas and passing them off as your own is very similar to stealing money or assets. So people who have demonstrated they are willing to steal ideas are better off avoided as they might be willing to steal your money/crypto as well. Now does this mean that people should not be leveraging other ideas or knowledge? Of course not, that is one of the things that makes open-source blockchain and tech in general so special. Everyone can learn from one another and build off each other which ultimately speeds. But blindly copying someone else's whitepaper does not really fall under this category. If a team ends up copying large sections of another team's whitepaper without citing their source or giving credit, it is usually a bad sign and something you would want to consider while evaluating the project.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 10,
    tag: "DT10-10",
    category: "Development Team",
    name: "Spelling Errors",
    question:
      "Are there grammar, spelling, and punctuation errors in the Whitepaper or webpage?.",
    worksteps: [
      "A. Copy text from whitepaper and website and paste into Grammarly using this link (https://www.grammarly.com/plagiarism-checker). ",
      "B. Grammarly is free, but if you do not wish to download it, perform manual review for grammar, spelling, and punctuation errors.",
      "C. In general a few small errors are OK. If there are large numbers of grammar spelling and punctuation errors, then answer this question No.",
      "D. Include a summary of the results into the box below.",
    ],

    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 0.5 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Most serious teams that are truly building something significant take a lot of pride in what they do. They like to make sure that everything is presented as the best version of itself and take the time and effort to review things multiple times with multiple people. As a result of this effort, there usually aren't too many errors to be found. This is contrasted against teams that have hastily put something together as fast as possible to exit scam or rug pull before quickly moving on to the next one. If a team has no real intention of bringing this product to market or sticking around long enough to see it through, they usually aren't spending all the time and energy to ensure everything is perfect. So if you are seeing a whitepaper that is full of spelling, grammar, and punctuation errors, that can be an indication that this team has not taken anything very seriously and may have bad intentions. Of course, this is not a guarantee and it's possible for an amazing project to have plenty of flaws in the whitepaper or a malicious project to have a flawless whitepaper. It is just one of the many things we look at when assessing a project on the whole. ",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 11,
    tag: "CT1-11",
    category: "Community",
    name: "Twitter",
    question: "How many followers does the project have on Twitter? ",
    worksteps: [
      "A. Check the project website to see if it includes a link to its twitter profile.",
      "B. If it does not, open twitter and type the project name.",
      "C. Review results to ensure you are looking at the correct account.",
      "D. Note the number of followers in the box below (enter an integer only, no commas or letters).",
    ],
    options: [
      { id: 1, name: "<1000", value: 0.0 },
      { id: 2, name: "1000 to 5000", value: 0.25 },
      { id: 3, name: ">5K", value: 0.5 },
      { id: 4, name: "N/A", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "You have likely seen this a hundred times before. There is a project that does nothing, has no use case, and goes up 30,000 percent in a year. I would like to tell you that only quality projects go up in value but that is far from the case. Hype and marketing are huge determinants in a project rising in value, and a large part of that is due to the community that is behind the project. And this doesn't just apply to meme coins or projects with little to no utility. Serious projects will also be affected by the size and strength of the community behind them. Adoption is key to success and survival, and chains or tokens with millions or supporters are already further along in terms of adoption than ones with a couple hundred. Not to mention the projects with a million people behind them are constantly writing, posting, and talking about the projects which generate new interest from others who might not have been familiar with it yet. So taking a look at the size and quality of a community behind any crypto project will usually give you invaluable information on if it will be a wise investment or not. But these can always be manipulated, which we cover in the next point.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 12,
    tag: "CT2-12",
    category: "Community",
    name: "Real Followers",
    question:
      "For the twitter account, does it appear to have actual followers or bots/paid followers?",
    worksteps: [
      "A. Review 10 or more tweets from the project and note the number of likes, comments, and retweets it has.",
      "B. Compare the total number of followers to the average number of likes or comments they receive on posts.",
      "C. If on average the number of likes is less than .5% of the followers, this suggests that the followers are not real. This is not a hard rule so will need to exercise judgement.",
      "D. Go to socialblade.com and review the follower activity (instructions here https://m.youtube.com/watch?v=9fj8Ng7w21U&feature=youtu.be)",
      "E. Write a summary of your findings in the box below.",
    ],
    options: [
      { id: 1, name: "Bots", value: 0.0 },
      { id: 2, name: "Real", value: 2.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "As discussed in the last point, community is important to the success of a project. But simply looking at the number of followers is insufficient. This is because there are a LOT of projects out there that have recognized how important a community is to a project, and simply buy thousands of followers to give the appearance that they have a large organic community behind them. Now can a project buy followers and still end up being a good investment? Of course they can. But we have already covered honesty and integrity in the other points, and that still applies here. Most legitimate projects will gain a following organically because they are high quality and people can recognize that. Low-quality projects that don't have much to offer will usually be the culprits in purchasing followers, which are typically the types of investments you would want to avoid.  So doing a little extra leg work in reviewing the posts to see how much actual engagement they get will be a good indicator if the followers are real or not. Someone with 50K followers who gets 5 to 10 likes is probably purchasing them. Someone who has no other people commenting or posting to their page probably doesn't have many real followers. And unfortunately, the really crafty projects who are on top of everything will also buy likes for their posts to avoid being discovered. But those will typically be something you can spot by looking through the people who engaged and seeing how many connections or followers they have. If they are all super low, it's a good chance they are paid bots.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 13,
    tag: "CT3-13",
    category: "Community",
    name: "Discord",
    question: "How many members does the project have on discord? ",
    worksteps: [
      "A. Check the project website to see if it includes an invite link to its Discord.",
      "B. If it does not, you will need to find an invite link to access the discord server. Check the projects twitter page for this.",
      "C. Note the number of followers in the box below (enter an integer only, no commas or letters).",
    ],
    options: [
      { id: 1, name: "<1000", value: 0.0 },
      { id: 2, name: "1000 to 10K", value: 0.25 },
      { id: 3, name: "10K+", value: 0.5 },
      { id: 4, name: "N/A", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "This is a very similar concept to the one on Twitter. I am copying it here again for your convenience. You have likely seen this a hundred times before. There is a meme coin that does nothing, has no use case, and it goes up 30,000 percent in a year. I would like to tell you that only quality projects go up in value but that is far from the case. Hype and marketing are huge determinants in a project rising in value, and a large part of that is due to the community that is behind the project. And this doesn't just apply to meme coins or projects with little to no utility. Serious projects will also be affected by the size and strength of the community behind them. Adoption is key to success and survival, and chains or tokens with millions or supporters are already further along in terms of adoption than ones with a couple hundred. Not to mention the projects with a million people behind them are constantly writing, posting, and talking about the projects which generate new interest from others who might not have been familiar with it yet. So taking a look at the size and quality of a community behind any crypto project will usually give you invaluable information on if it will be a wise investment or not. But these can always be manipulated, which we cover in the next point.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 14,
    tag: "CT4-14",
    category: "Community",
    name: "Discord Activity",
    question: "Does their Discord appear to have an active environment?",
    worksteps: [
      "A. Note the number of members compared to the number of people online. A large percentage of members online suggests an active environment.",
      "B. Scan the recent activity. If there are several comments  by different accounts each day, this also suggests an active environment.",
      "C. Comment on activity in box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "This is a very similar concept to the one on Twitter. I am copying it here again for your convenience. You have likely seen this a hundred times before. There is a meme coin that does nothing, has no use case, and it goes up 30,000 percent in a year. I would like to tell you that only quality projects go up in value but that is far from the case. Hype and marketing are huge determinants in a project rising in value, and a large part of that is due to the community that is behind the project. And this doesn't just apply to meme coins or projects with little to no utility. Serious projects will also be affected by the size and strength of the community behind them.  Adoption is key to success and survival, and chains or tokens with millions or supporters are already further along in terms of adoption than ones with a couple hundred. Not to mention the projects with a million people behind them are constantly writing, posting, and talking about the projects which generate new interest from others who might not have been familiar with it yet. So taking a look at the size and quality of a community behind any crypto project will usually give you invaluable information on if it will be a wise investment or not. But these can always be manipulated, which we cover in the next point.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 15,
    tag: "CT5-15",
    category: "Community",
    name: "Collaborations/Giveaways",
    question: "Does the team promote collaboration events with other projects?",
    worksteps: [
      "A. Check on discord if there is a channel dedicated to collaborations.",
      "B. If so confirm on the collab participants discords if the events are real.",
      "C. If nothing is listed on Discord, review the project website for partnerships or collaborations.",
      "D. Note your findings in the box below.",
    ],

    options: [
      { id: 1, name: "Yes", value: 1.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Collaborations with other projects are an excellent way of promoting the project and expanding its community. In addition, if other successful or reputable projects are willing to collaborate with them, it shows a level of trust in that project that increases its credibility. So anytime you see high quality collaborations, that is usually a good sign. Here are a few questions you can think through while answering this question to help you put things into context. Feel free to include these answers when you are filling out the text box. How long has this project partnered with the other project? Is the history of their partnership reflected on the project’s website, public and private social media channels like Twitter and Discord, or other platforms? Is there cross-project utility? E.g. Holding another project’s NFTs or associated FTs earns you whitelist spots or NFT discounts, special cross-project 1/1 NFTs airdropped to holder wallets, etc.? Does the project have a track record of delivering on its side of these collaborations? Can this be verified by community members posting about it on social media platforms?",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 16,
    tag: "CT6-16",
    category: "Community",
    name: "Banishment",
    question: "Does the project unfairly ban members from social media?",
    worksteps: [
      "A. Join the projects Discord or Telegram.",
      "B. Locate the appropriate place for general questions.",
      "C. Tell the community you are researching this project and ask for their input on the subject.",
      "D. Summarize your findings in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 1.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Most honest projects will welcome difficult questions as they want to be open and transparent about everything. If a project is quick to ban members who question them, it can be a bad sign that they might not have answers to those questions and do not want others to begin asking them as well. This can be a fine line though. If someone is constantly making things up or purposely trying to undermine a project by spamming its social media with lies to make it look bad, then banning or blocking them could be appropriate. So you will have to use some judgement here to decide between those two cases.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 17,
    tag: "CT1-17",
    category: "Community",
    name: "Responsiveness",
    question: "Does the team respond to questions promptly and satisfactorily?",
    worksteps: [
      "A. Join the projects Discord or Telegram.",
      "B. Locate the appropriate place for general questions.",
      "C. Ask about something that has come up during your research you are unsure of.",
      "D. Assess if a satisfactory response from a team member or mod is received within 24 hours.",
      "E. Write your question, the team's response, and your assessment in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "As mentioned in the previous question, most legitimate projects welcome questions. They want people to learn about what they are offering and encourage people to ask questions about things they are unsure of or want to learn more about. Because of this, many teams will have dedicated moderators for their social media channels as well as their email address who will respond to people's questions. If you find yourself in a project's Discord or Telegram and cannot find someone associated with the team to respond to questions within a reasonable amount of time (usually within 24 hours is reasonable) then that is usually not a strong sign for that project. But this also doesn't mean that responding to questions quickly automatically means the project is legit. There are plenty of shady projects out there which will respond to your questions quickly. But oftentimes, a bad project will not have a lot of substance in the responses they give you. If you are seeing some warning signs while doing your research that you ask about respectfully, and you are unable to get a satisfactory response, that can be seen as a red flag. ",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 18,
    tag: "CT8-18",
    category: "Community",
    name: "Price Support",
    question:
      "Does the project team promote events to increase the floor price (such as sweeping floor, delist contests or bounties) ?",
    worksteps: [
      "A. Check on discord if there are any contests going on promoted by the project team.",
      "B. Check the project's official twitter feed for past tweets regarding contests promoted by the team.",
      "C. Note your findings in the box below.",
      "D. If the project has not minted, mark this question as N/A.",
    ],

    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 2, name: "No", value: 1.0 },
      { id: 3, name: "N/A", value: 1.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Although this can be seen as a price manipulation strategy on other assets, in the NFT world this practise is generally welcomed and encouraged by the community. The floor price is the cheapest item from the collection on sale on the secondary markets and therefore, promoting its acquisition or delist will rise the floor price and make the project more appealing, even if only momentarily. Most of the times, these events come in the form of a contest, where prizes are awarded to the community members. Besides having a direct impact on the floor value of the project, these initiatives also affect its overall activity on the secondary markets, which is an important metric when analyzing a project.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 19,
    tag: "MM1-19",
    category: "Mint Metrics",
    name: "Minting price",
    question: "Is/was the initial price set for the mint reasonable?",
    worksteps: [
      "A. Check the official website to see if the mint price has set.",
      "B. If it is not listed on the website, inquire about it in the Telegram or Discord.",
      "C. To determine if it is reasonable, compare it to other similar projects that had successful mints and secondary market sales.",
      "D. Note the mint price and your assessment of its reasonableness in the box below.",
      "E. If the mint price has not been set yet, mark N/A for this question.",
    ],

    options: [
      { id: 1, name: "Yes", value: 0.5 },
      { id: 2, name: "No", value: 0.0 },
      { id: 3, name: "N/A", value: 0.5 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Setting a reasonable price for minting a NFT makes it more affordable to more people, increasing the chances of making sales or even selling-out the collection. At the same time, setting a price too low can impact it's long term value. So finding the sweet spot here is difficult but also important. This of course will be subjective and vary from person to person as far as what is reasonable. In general, if it is priced similarly to other similar projects that have been successful, that can be considered reasonable while being far higher or lower would not be.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 20,
    tag: "MM2-20",
    category: "Mint Metrics",
    name: "Supply and demand",
    question:
      "Is the demand for the project considerably higher than the total supply of the collection?",
    worksteps: [
      "A. Check the website or discord to confirm how large is the supply available for the mint.",
      "B. Confirm how many members the community has on twitter and discord.",
      "C. Carefully check if the project team promoted invite contests (generally on discord).",
      "D. Note your findings in the box below.",
      "E. If the project has already minted, mark this question as N/A.",
    ],

    options: [
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
      { id: 3, name: "N/A", value: 2.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "The supply and demand of a collection is essentially what guarantees that a project will sell-out. If the mint is already over, demand for the NFT will be responsible for maintaining a good level of activity in the secondary markets. Ideally, a project should have a number or follower/members considerably superior to the supply of the collection. Regarding community followers/members sometimes projects engage in invite contests where prizes are given to the top contestants, generally in the form of whitelist spots. These mechanisms can cause an abnormal increase of followers/members and should be taken into consideration when analysing the project and trying to deduce if the project demand is high enough to assure a sell-out of the collection.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 21,
    tag: "MM3-21",
    category: "Mint Metrics",
    name: "Minting process",
    question:
      "How will/did the minting happen? ADA transfer to an address dropped or through a minting platform?",
    worksteps: [
      "A. Check the official website or social media for information regarding the minting process.",
      "B. Note how the minting will happen? ADA transfer to an address dropped or through a minting platform?.",
      "C. Is the collection verified and have a policy ID?",
      "D. Note the number of members in the box below.",
      "E. If the project has not released how the mint will occur, mark this question as N/A.",
    ],

    options: [
      { id: 1, name: "Address drop", value: 0.0 },
      { id: 2, name: "Minting platform/Multi-sig", value: 1.0 },
      { id: 3, name: "N/A", value: 1.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "The mint day is the culmination of months of effort to guarantee the success of the project and also marks a new beginning where the investors will finally be able to acquire their NFT and enjoy the utility features of the project. Unfortunately, for many projects this process isn't smooth at all, and a lot of problems can happen such as scams on Discord, high network congestion causing the delivery of the NFT to take too long, and sometimes you end up being refunded because the project sold out before your transaction was processed. These problems are generally associated with minting by address drop, where a team member drops an address on Discord or on the official website and the investors have to send a specific value to it receiving afterwards the corresponding NFT. Lately, projects have other ways of minting, such as minting platforms or multi-sig, which are much safer for the community, some platform such as NMKR requires KYC for creators, faster (in most cases there is no need for refunds), cause much less congestion on the network, and reduce significantly the chances of failed transactions. Projects that consider these alternatives strive to make the minting process a better experience to the community and not an ordeal.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 22,
    tag: "MM4-22",
    category: "Mint Metrics",
    name: "Mint Timeline",
    question: "How much time passed between founding the project and minting?",
    worksteps: [
      "A. Review the website or whitepaper and note if a date the project was founded is listed.",
      "B. Compare that to when the projects Twitter was created to see if they are similar.",
      "C. It is possible they purchased an older Twitter account, so scan through and look at when the first Tweets about the project were sent from the account.",
      "D. Check the website to see when the minting date is/was and note how much time passed between founding date and mint.",
      "E. If the collection has not set a date yet, mark this question as N/A.",
    ],
    options: [
      { id: 1, name: "< 14 days", value: 0.0 },
      { id: 2, name: "15 days to 45 days", value: 0.25 },
      { id: 3, name: "> 45 days", value: 0.5 },
      { id: 4, name: "N/A", value: 0.5 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Doing a project right will usually take a good amount of time and effort. Projects will want to work on building a community and generating interest is their NFTs, which usually cannot be done overnight. If you see a very short window from the time the project was founded to when the minting begins, it can give the impression that not much effort is going into these things and the team is just trying to make a quick buck.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 23,
    tag: "MM5-23",
    category: "Mint Metrics",
    name: "Rarity chart",
    question:
      "Does the collection have or is planned have a rarity chart of the traits of its NFT?",
    worksteps: [
      "A. Check the official website of the project.",
      "B. Check on discord if there is information regarding the rarity of the traits or if there will be in the future.",
      "C. For Cardano NFTs, go to CNFT.Tools, type in the project name in the search, and see if the project appears with rarity features listed.",
      "D. If the collection has no rarity features and it is only based on utility, N/A should be chosen.",
    ],

    options: [
      { id: 1, name: "Yes", value: 1.0 },
      { id: 2, name: "No", value: 0.0 },
      { id: 3, name: "N/A", value: 1.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "A common feature that is generally part of the collections (especially on PFP types), is the existence of a wide list of different traits, such as background, eye effects, weapons wielded, clothing, headpieces or even music. The integration of these traits generates a unique NFT. In the majority of the cases, these traits have a rarity associated to them. Some are common, others will be rarer. Additionally, there usually are a few 1/1 NFT in the collection, which have a completely unique appearance. Therefore, the comparison between the floor price and the top rank price varies considerably making the most valuable ones more desirable. In some projects, the higher rank NFTs also have more privileges associated with them regarding utility, such as regular airdrops or priority on whitelists. In many cases, the rarity of each trait is only published after the mint and afterwards integrated on websites like CNFT.Tools (Cardano blockchain). Here are some guiding questions to think about while answering this question. Feel free to include information about them in the text box when filling out your response: Did the project really think through their rarity traits? Are there benefits to trying to mint rarer NFTs or buy them from secondary markets? Are certain rare traits tied to partnering projects, hence helping the entire NFT ecosystem? If the project is a video game project, and rarity traits earn you special “powers” or “perks” in the game’s ecosystem, how does the project keep their ecosystem democratic for holders of less rare NFTs?",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 24,
    tag: "SM1-24",
    category: "Secondary Market",
    name: "Minted",
    question: "Has the collection already minted?",
    worksteps: [
      "A. This section only applies for projects which have already minted. If it has not, skip this section by selecting No and clicking next until it reaches the end.",
      "B. If No is selected, it will not impact the overall score and this entire section is N/A.",
    ],

    options: [
      { id: 1, name: "Yes", value: 0.0 },
      { id: 404, name: "No", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "You might be researching a project before the minting started, or one that has already minted and is more established. If it has not minted yet, then including all of these questions in the overall scoring would skew it. For this reason, we ask this initial question and remove it from the scoring if the answer is No. ",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 25,
    tag: "SM2-25",
    category: "Secondary Market",
    name: "Locked Policy",
    question:
      "Is the token minting policy locked so that no changes can be made? Yes or No",
    worksteps: [
      "A. Obtain the policy ID from project website. You may have to look around, but most minted tokens will list the policy on the website so you know you are getting the right token.",
      "B. Copy policy into pool.pm.",
      "C. Under policy, ensure there is a lock symbol which signifies that policy is locked and cannot be changed (closed lock icon signifies locked policy).",
      "D. Copy in policy ID and note if policy is locked in box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 0.25 },
      { id: 2, name: "No", value: 0.0 },
      { id: 404, name: "N/A", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Ask a Bitcoin Maxi why they love Bitcoin so much and there is a good chance one of their responses will be 'fixed and unchanging monetary policy'. They are not wrong about this being a good feature, as it ensures that everyone knows the rules and can plan accordingly. You know how many tokens exist and know if more can be created. Most people wouldn't be too thrilled if the makers of the NFT they just purchased decided to mint more which dilute the value of the ones they currently hold. You can make sure this is not possible if the policy is locked and can no longer be changed. If that is the case, then whatever the rules are when the tokens were minted will always apply and you do not run the risk of this being altered later down the line. It is also worth noting that each policy ID is unique to that token. It is possible to have 100 different tokens all with the same name, ticker symbol, and icon image. Some scammers might try to trick you by listing a copied token for sale on a DEX which appears to be the same (same name and ticket). But no matter what, the policy ID cannot be copied. It is a good practice to check the policy ID which is usually listed on the website and ensure you are purchasing the correct tokens.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 26,
    tag: "SM3-26",
    category: "Secondary Market",
    name: "Number of unique owners",
    question: "For existing collections, what percentage are unique owners?",
    worksteps: [
      "A. Confirm the policy ID on the official website or social media.",
      "B. Check on second market websites such as CNFT.Tools or CNFT Jungle for the number of items in the collection and the corresponding number of holders. Make sure it is the correct policy ID.",
      "C. Confirm the numbers above on a blockchain scan tool through the policy ID of the collection.",
    ],
    options: [
      { id: 1, name: "0 to 25%", value: 0.0 },
      { id: 2, name: "26% to 50%", value: 0.75 },
      { id: 3, name: ">50%", value: 1.5 },
      { id: 404, name: "N/A", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Generally it is seen as a good sign when more than half of the collection items are held in unique wallets. This metric is important for the project health because it relates with the project activity on second markets. Since part of the income comes from royalties (the other part in most cases is the minting process), more unique wallets tend to mean a higher activity and therefore, more royalties to the project. A healthy project needs funds to be able to pay it's team and continually grow and promote its product. In addition, having a large number of unique owners is healthy for a project vs having a small number of people own the entire supply. Having a few whales own the majority of the collection means they can dictate the floor price. Community is also an important aspect of an NFT project so having a large number of holders translates to a large community.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 27,
    tag: "SM4-27",
    category: "Secondary Market",
    name: "Floor price history ",
    question: "Has the floor price growth been favorable for the project?",
    worksteps: [
      "A. Confirm the policy ID on the official website or social media.",
      "B. Check the original mint price. This can usually be found on the website or discord (FAQ, mint-info, etc).",
      "C. Check on jpeg.store for floor price history by entering the project name and selecting activity. Make sure it is the correct policy ID.",
      "D. Confirm the above numbers on a market analytics platform according to the specific blockchain (such as nftjungle.io). Make sure it is the correct policy ID.",
      "E. Note: If the floor price has increased but ONLY because of floor price-increasing efforts / market manipulation (Question CT12-22), mark this questions NO.",
      "F. Summarize your findings in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 1.25 },
      { id: 2, name: "No", value: 0.0 },
      { id: 404, name: "N/A", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "Regarding existing NFT collections, the test of time is what determines the long term success of the project. Bored Ape Yacht Club had an initial price of 0.08 ether (around $190) back in April 23, 2021. On July 10, 2022 the floor price was 99.7 ether (around $116K). From the mint day until now, the community has witnessed a constant growth of the floor price and trade volume, two important metrics that allow the general public to determine if a project is worth investing on or not. Therefore, it is recommended that future investors research through market analytics platforms (or any other website that presents statistics regarding NFT), the existing projects they are planning on investing. Checking that a projects price has increased from the original mint price is a good indicator that the project is doing well and may continue to do so.",
    files: [],
    images: [],
    video: [],
  },
  {
    id: 28,
    tag: "SM5-28",
    category: "Secondary Market",
    name: "Availability",
    question: "Did the mint sell-out without any change to the initial supply?",
    worksteps: [
      "A. Confirm the policy ID of the NFT on the official website or social media.",
      "B. Confirm the initial collection size on the official website or social media.",
      "C. Check the total minted tokens on blockchain analysis platforms or second market websites.",
      "D. Summarize your findings in the box below.",
    ],
    options: [
      { id: 1, name: "Yes", value: 2.0 },
      { id: 2, name: "No", value: 0.0 },
      { id: 404, name: "N/A", value: 0.0 },
    ],
    answer: null,
    textarea: "",
    purpose:
      "The size of the collection is an important decision when creating a new NFT. The size of a collection can range from a few hundred to thousands but in the end, the principle of supply and demand should be taken into consideration by the project. A collection with 10.000 NFTs but with a community of only 1000 or 2000 members can have difficulty selling out before the end date of the public minting, which can mean a lack of general interest in the project. To counter this lack of demand, many teams decide to change the initial number of tokens which can cause the illusion that the project was highly demanded.",
    files: [],
    images: [],
    video: [],
  },
];
